#!/usr/bin/env python3
"""
Extract types and templates from vanilla EU5 GUI files.

Creates GUI files containing only the type/template definitions from vanilla files,
allowing dependent mods to override the original files (for top-level widgets like
lateralviews) without losing the shared type/template definitions.

Usage: python tools/extract_vanilla_types.py
"""

import sys
from pathlib import Path

GAME_GUI_DIR = Path(r"C:\Steam\steamapps\common\Europa Universalis V\game\in_game\gui")
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "in_game" / "gui" / "vanilla"

VANILLA_FILES = [
    "foreign_country_lateralview.gui",
    "government_lateralview.gui",
    "ingame_topbar.gui",
    "location_window.gui",
    "outliner_entries.gui",
    "single_unit_window.gui",
    "societal_values_lateralview.gui",
    "technology_lateralview.gui",
    "war_lateralview.gui",
]

BOM = "\ufeff"


def parse_braces(line):
    """Return (net_depth_change, has_open) for a line, ignoring strings and comments."""
    in_string = False
    depth = 0
    has_open = False
    for ch in line:
        if ch == "#" and not in_string:
            break
        if ch == '"':
            in_string = not in_string
        if not in_string:
            if ch == "{":
                depth += 1
                has_open = True
            elif ch == "}":
                depth -= 1
    return depth, has_open


def find_block_end(lines, start):
    """Find the end of a brace-delimited block starting at `start`. Returns end index (exclusive)."""
    brace_depth = 0
    seen_open = False
    i = start
    while i < len(lines):
        delta, has_open = parse_braces(lines[i])
        brace_depth += delta
        if has_open:
            seen_open = True
        i += 1
        if seen_open and brace_depth <= 0:
            break
    return i


def extract_types_templates(content):
    """Extract variables, templates, and types blocks from GUI file content.

    Returns (extracted_lines, stats).
    """
    lines = content.split("\n")
    result = []
    buffer = []  # Pending comment/blank lines before next block
    stats = {"variables": 0, "templates": 0, "types_blocks": 0, "skipped": 0}
    i = 0

    while i < len(lines):
        stripped = lines[i].strip()

        # Collect comments and blank lines in buffer
        if not stripped or stripped.startswith("#"):
            buffer.append(lines[i])
            i += 1
            continue

        # Variable definition (@name = value)
        if stripped.startswith("@"):
            result.extend(buffer)
            buffer = []
            result.append(lines[i])
            stats["variables"] += 1
            i += 1
            continue

        # Template block
        if stripped.startswith("template "):
            result.extend(buffer)
            buffer = []
            block_end = find_block_end(lines, i)
            result.extend(lines[i:block_end])
            result.append("")
            stats["templates"] += 1
            i = block_end
            continue

        # Types block
        if stripped.startswith("types "):
            result.extend(buffer)
            buffer = []
            block_end = find_block_end(lines, i)
            result.extend(lines[i:block_end])
            result.append("")
            stats["types_blocks"] += 1
            i = block_end
            continue

        # Any other top-level block (widget, lateralview, select_menu, etc.) — skip
        buffer = []
        stats["skipped"] += 1
        if "{" in stripped:
            i = find_block_end(lines, i)
        else:
            i += 1

    return result, stats


def process_file(filename):
    """Process a single vanilla GUI file and write extracted types/templates."""
    input_path = GAME_GUI_DIR / filename
    if not input_path.exists():
        print(f"  SKIP: {input_path} not found")
        return False

    content = input_path.read_text(encoding="utf-8-sig")
    extracted, stats = extract_types_templates(content)

    # Strip trailing blank lines
    while extracted and not extracted[-1].strip():
        extracted.pop()

    if not stats["variables"] and not stats["templates"] and not stats["types_blocks"]:
        print(f"  SKIP: No types or templates found")
        return False

    stem = filename.removesuffix(".gui")
    output_name = f"cmf_{stem}_vanilla_types.gui"
    output_path = OUTPUT_DIR / output_name

    header = [
        f"# Vanilla types and templates extracted from {filename}",
        "# Auto-generated by tools/extract_vanilla_types.py",
        "",
    ]

    output_content = BOM + "\r\n".join(header + extracted) + "\r\n"
    output_path.write_bytes(output_content.encode("utf-8"))

    parts = []
    if stats["variables"]:
        parts.append(f"{stats['variables']} vars")
    if stats["templates"]:
        parts.append(f"{stats['templates']} templates")
    if stats["types_blocks"]:
        parts.append(f"{stats['types_blocks']} types blocks")
    print(f"  OK: {output_name} ({', '.join(parts)})")
    return True


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Source: {GAME_GUI_DIR}")
    print(f"Output: {OUTPUT_DIR}\n")

    count = 0
    for filename in VANILLA_FILES:
        print(f"Processing {filename}...")
        if process_file(filename):
            count += 1

    print(f"\nDone: {count}/{len(VANILLA_FILES)} files processed")
    return 0 if count > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
